name: 'Test, Build and Deploy Artifact'

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      TF_API_TOKEN:
        required: true
 
jobs:
  test-build-deploy:
    name: 'Test, Build and Deploy Artifact'
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}


    - name: Terraform format
      working-directory: .terraform
      run: terraform fmt -check

    - name: Go Test
      run: go test -v ./...


    - name: Go Build
      run: go build -v -o LambdaHandler

    - name: Go Package Deploy Artifact
      run:  |
        zip .terraform/deploy_artifact.zip LambdaHandler

    - name: Begin Infrastructure Deployment
      run: echo "Deploying Infrastructure to ${{ inputs.environment }}"

    - name: Set Environment Variables
      run: |
        case ${{ inputs.environment }} in
          development)  echo "TF_WORKSPACE=smalldomains--forwarder-dev" >> $GITHUB_ENV;;
          production)   echo "TF_WORKSPACE=smalldomains--forwarder-prod" >> $GITHUB_ENV;;
          *)            echo "${{ inputs.environment }} is an unrecognised environment"; exit 1;;
        esac

    - name: View Environment Variables
      run: echo "Using TF_WORKSPACE of $TF_WORKSPACE"
      

    - name: Terraform Init
      working-directory: .terraform
      run: terraform init

    - name: Terraform Validate
      working-directory: .terraform
      run: terraform validate

    - name: Terraform Plan
      working-directory: .terraform
      run: terraform plan -var-file=tfvars/${{ inputs.environment }}.tfvars

    - name: Terraform Apply
      working-directory: .terraform
      run: terraform apply -auto-approve -var-file=tfvars/${{ inputs.environment }}.tfvars